/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIconPicker: typeof import('./src/components/ElIconPicker.vue')['default']
    MenuSwitch: typeof import('./src/components/icon/MenuSwitch.vue')['default']
    RightToolbar: typeof import('./src/components/RightToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
